load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = [
    "//src/main/go/org/alberthsuu:__subpackages__",
])

go_library(
    name = "arithmetic",
    srcs = ["arithmetic.go"],
    importpath = "org/alberthsuu/custommath",
)
