load("@io_bazel_rules_go//go:def.bzl", "go_test")

go_test(
    name = "hello_test",
    srcs = [
        "hello_test.go",
    ],
    # embed = [":foo_lib"],
    # deps = [
    #     "//testtools",
    #     "@org_golang_x_utils//morestuff",
    # ],
)
